development:
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  database: todotopia_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  database: todotopia_test
  pool: 5

