#!/usr/bin/env bash

source ~/.bashrc

RAILS_ENV="${RAILS_ENV:-development}"

enter $release_path

info "Run bundler..."
bundle install 

info "Running migrations..."
rake db:migrate --trace >> ~/shared/log/migrate.log 2>&1

info "Updating cron via whenever..."
whenever --set environment=production -w 

mkdir -p tmp/pids

info "Restarting unicorns..."
bdsm unicorn restart

rake hoptoad:deploy TO=$environment
